spring:
  application:
    name: gateway-service

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    student:
      url: http://localhost:8090
ribbon:
  eureka:
    enabled: false
